version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - influxdb:/var/lib/influxdb2
    ports:
      - '8086:8086'
  nodered:
    image: nodered/node-red
    container_name: nodered
    volumes:
      - nodered:/data
    ports:
      - '1880:1880'
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - '9001:9001'
      - '1883:1883'
volumes:
  grafana:
  influxdb:
  nodered: