version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      EULA: "true"
      TYPE: ${SERVER_TYPE}
      VERSION: ${SERVER_VERSION}
      CONSOLE: "false"
      MOTD: ${SERVER_MOTD}
      MEMORY: ${SERVER_MEMEORY}
      SERVER_NAME: ${SERVER_NAME}
      OVERRIDE_SERVER_PROPERTIES: "true"
      WHITELIST: ${SERVER_WHITELIST}
      OPS: ${SERVER_OPS}
      ENFORCE_WHITELIST: "true"
      ENABLE_RCON: "true"
    ports:
      - 25565:25565
    volumes:
      - /opt/minecraft/data:/data